# Generated by Django 5.0.4 on 2024-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='image',
            field=models.ImageField(default='default/no_image_available.jpg', upload_to='images/'),
        ),
    ]
