# Generated by Django 5.0.4 on 2024-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='description',
        ),
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('cancelled', 'Cancelled')], default='planned', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
