# Generated by Django 5.0.4 on 2024-05-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
